src/Biotopedia/PisciothequeBundle/Entity/Famille.php
<?php
//src/Biotopedia/PisciothequeBundle/Entity/Famille.php
namespace Biotopedia\PisciothequeBundle\Entity;

use Doctrine\ORM\Mapping as ORM; //Pour la notation
use Symfony\Component\Validator\Constraints as Assert; //Pour formulaires composés de plusieus Type
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Famille
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Biotopedia\PisciothequeBundle\Entity\FamilleRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Famille
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var datetime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var datetime
     *
     * @ORM\Column(name="updated", type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @var string
     *
     * @ORM\Column(name="scientific_name", unique=true, type="string", length=100)
     * @Assert\NotBlank()
     */
    private $scientific_name;

    /**
     * @var string
     *
     * @ORM\Column(name="common_name", unique=true, type="string", length=100)
     * @Assert\NotBlank()
     */
    private $common_name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    // Attribut pour stocker le nom du dossier temporairement lors de la suppression
    /**
     * @var string
     *
     * @ORM\Column(name="temp_directoryname", type="string", length=255, nullable=true)
     */
    private $temp_directoryname;

    /**
     * @var string
     *
     * @ORM\Column(name="image_directory", type="text")
     */
    private $image_directory;

    //Chaque Famille néccesite une Image (JoinColumn(nullable=false)), donc cascade sur persite car 
    //on doit persiter une Image quand je persite une Famille.
    /**
    * @ORM\OneToOne(targetEntity="Biotopedia\CoreBundle\Entity\Image", cascade={"persist", "remove", "merge"})
    */
    private $image;

    //'s' car une famille est liée à plusieurs poissons.
    //L'entité inverse Famille doit être au courant des caractéristiques
    //de la relation, définies dans l'annotation de l'entité propriétaire Poisson.
    //Le mappedBy correspond donc à l'attribut de l'entité propriétaire (Poisson)
    //pointant vers l'entité inverse (Famille) : private $famille
    /**
    * @ORM\OneToMany(targetEntity="Poisson", mappedBy="famille", cascade={"persist", "remove", "merge"}, orphanRemoval=true)
    */
    private $poissons;

    /**
    * @ORM\Column(name="nb_poissons", type="integer")
    */
    private $nb_poissons = 0;

    /**
    * @ORM\ManyToMany(targetEntity="Biotopedia\UsersBundle\Entity\User", inversedBy="familles")
    */
    private $auteurs;

    ////////////////////////////////////////////////////////////////////////////////
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->created  = new\DateTime();
        $this->poissons = new ArrayCollection();
        $this->auteurs = new ArrayCollection();
    }
    ////////////////////////////////////////////////////////////////////////////////
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Famille
     */
    public function setCreated($created)
    {
        $this->created = $created;
    
        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Famille
     */
    public function setUpdated(\Datetime $updated)
    {
        $this->updated = $updated;
    
        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set scientific_name
     *
     * @param string $scientific_name
     * @return Famille
     */
    public function setScientificName($scientific_name)
    {
        $this->scientific_name = $scientific_name;

        return $this;
    }

    /**
     * Get scientific_name
     *
     * @return string 
     */
    public function getScientificName()
    {
        return $this->scientific_name;
    }

    /**
     * Set common_name
     *
     * @param string $common_name
     * @return Famille
     */
    public function setCommonName($common_name)
    {
        $this->common_name = $common_name;
    
        return $this;
    }

    /**
     * Get common_name
     *
     * @return string 
     */
    public function getCommonName()
    {
        return $this->common_name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Famille
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set temp_directoryname
     *
     * @param string $tempDirectoryname
     * @return Famille
     */
    public function setTempDirectoryname($tempDirectoryname)
    {
        $this->temp_directoryname = $tempDirectoryname;
    
        return $this;
    }

    /**
     * Get temp_directoryname
     *
     * @return string 
     */
    public function getTempDirectoryname()
    {
        return $this->temp_directoryname;
    }

    /**
     * Set image_directory
     *
     * @param string $imageDirectory
     * @return Famille
     */
    public function setImageDirectory($imageDirectory)
    {
        $this->image_directory = $imageDirectory;
    
        return $this;
    }

    /**
     * Get image_directory
     *
     * @return string 
     */
    public function getImageDirectory()
    {
        return $this->image_directory;
    }
    
    // rajouter $image = null: public function setImage(\Biotopedia\PisciothequeBundle\Entity\Image $image = null)
    // en cas de relation facultative.
    /**
     * Set image
     *
     * @param \Biotopedia\CoreBundle\Entity\Image $image
     * @return Famille
     */
    public function setImage(\Biotopedia\CoreBundle\Entity\Image $image = null)
    {
        $this->image = $image;
    
        return $this;
    }

    /**
     * Get image
     *
     * @return \Biotopedia\PisciothequeBundle\Entity\Image 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set nbPoissons
     *
     * @param integer $nbPoissons
     * @return Famille
     */
    public function setNbPoissons($nbPoissons)
    {
        $this->nb_poissons = $nbPoissons;
    
        return $this;
    }

    /**
     * Get nbPoissons
     *
     * @return integer 
     */
    public function getNbPoissons()
    {
        return $this->nb_poissons;
    }

    ////////////////////////////////////////////////////////////////////////////
    /**
     * Add poissons
     *
     * @param \Biotopedia\PisciothequeBundle\Entity\Poisson $poisson
     * @return Famille
     */
    public function addPoisson(\Biotopedia\PisciothequeBundle\Entity\Poisson $poisson)
    {
        $this->poissons[] = $poisson;

        // On lie le poisson à la famille
        $poisson->setFamille($this);
    
        return $this;
    }

    /**
     * Remove poissons
     *
     * @param \Biotopedia\PisciothequeBundle\Entity\Poisson $poissons
     */
    public function removePoisson(\Biotopedia\PisciothequeBundle\Entity\Poisson $poisson)
    {
        $this->poissons->removeElement($poisson);
    }

    /**
     * Get poissons
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPoissons()
    {
        return $this->poissons;
    }
    //////////////////////////////////////////////////////////////////////////////////
    /**
    * Add users
    *
    * @param \Biotopedia\UsersBundle\Entity\User $user
    * @return Famille
    */
    public function addAuteur(\Biotopedia\UsersBundle\Entity\User $user)
    {
        // Ici, on utilise l'ArrayCollection vraiment comme un tableau
        $this->auteurs[] = $user;

        return $this;
    }

    /**
    * Remove users
    *
    * @param \Biotopedia\UsersBundle\Entity\User $user
    */
    public function removeAuteur(\Biotopedia\UsersBundle\Entity\User $user)
    {
        // Ici on utilise une méthode de l'ArrayCollection, pour supprimer la catégorie en argument
        $this->auteurs->removeElement($user);
    }

    /**
    * Get auteurs
    *
    * @return \Doctrine\Common\Collections\Collection 
    */
    // Notez le pluriel, on récupère une liste de catégories ici !
    public function getAuteurs()
    {
        return $this->auteurs;
    }

    //////////////////////////////////////////////////////////////////////////////////
    public function increasePoisson()
    {
        $this->nb_poissons++;
    }

    public function decreasePoisson()
    {
        $this->nb_poissons--;
    }

    /**
     * @ORM\PrePersist
     */
    public function increase()
    {
        $this->getAuteur()->increaseFamille();
    }

    /**
     * @ORM\PreRemove
     */
    public function decrease()
    {
        $this->getAuteur()->decreaseFamille();
    }
    //////////////////////////////////////////////////////////////////////////////////
    /**
    * @ORM\PrePersist()
    * @ORM\PreUpdate()
    */
    public function preCreation()
    {
        // Si image_directory existe c'est un update 
        if(null !== $this->image_directory){
            $this->temp_directoryname = $this->image_directory;
            $this->setUpdated(new \Datetime());
        }

src/Biotopedia/PisciothequeBundle/Form/Type/FamilleType.php
<?php
//src/Biotopedia/PisciothequeBundle/Form/Type/FamilleType.php
namespace Biotopedia\PisciothequeBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

use Biotopedia\CoreBundle\Form\Type\ImageType;

class FamilleType extends AbstractType
{
 //Facultatif mais c'est mieux de déclaré la class ratachée à ce formulaire
  public function setDefaultOptions(OptionsResolverInterface $resolver)
  {
    $resolver->setDefaults(array(
      'data_class' => 'Biotopedia\PisciothequeBundle\Entity\Famille'
    ));
  }

  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    $builder
      ->add('common_name', 'text')
      ->add('scientific_name', 'text')
      ->add('description','textarea')
      ->add('image', new ImageType())
      /*
      * Rappel :
       ** - 1er argument : nom du champ, ici « poissons », car c'est le nom de l'attribut
       ** - 2e argument : type du champ, ici « collection » qui est une liste de quelque chose
       ** - 3e argument : tableau d'options du champ
       ** allow_add et allow_delete, autorisent au formulaire l'ajout d'entrées en plus dans la collection, ainsi que d'en supprimer
       ** Normalement, le framework de formulaire modifierait les poissons d'un objet Famille sans 
       ** jamais appeler setPoissons. En définissant by_reference à false, setPoissons sera appelé
      */
      ->add('poissons', 'collection', array(
        'type'         => new PoissonMiniType(),
        'allow_add'    => true,
        'allow_delete' => true,
        'by_reference' => false
      )); 
  }

  public function getName()
  {
    return 'familleType';
  }
}

src/Biotopedia/PisciothequeBundle/Resources/views/Famille/addFamille.html.twig
{# src/Biotopedia/PisciothequeBundle/Resources/views/Famille/addFamille.html.twig #}

{% extends "BiotopediaPisciothequeBundle::layout.html.twig" %}

{% block title %}
  Ajouter une famille - {{ parent() }}
{% endblock %}

{% block titre %}
  {{ parent() }}<h3 class="content-titre">Ajouter une famille</h3>
{% endblock %}

{% block biotopediapisciotheque_content %}
  <section id="form-addFamille">
  	<p>Vous vous apprêtez à ajouter une nouvelle famille dans la pisciothèque du site Biotopedia !</p>
  	<form action="{{ path('biotopedia_pisciotheque_addFamille') }}" method="post" {{ form_enctype(form) }}>

      <div class="error">
        {{ form_errors(form) }}{# Les erreurs générales du formulaire. #}
      </div>

  		<table id="famille-identite-table-form" class="famille-table-form">
        <tr>
          <th>{{ form_label(form.scientific_name, "Nom Scientifique") }}</th>
        	<th>{{ form_label(form.common_name, "Nom Commun") }}</th>
          <th>{{ form_label(form.image, "Photo de la famille") }}</th>
        </tr>
        <tr>
          <td class="popup">
            {{ form_errors(form.scientific_name) }}
            {{ form_widget(form.scientific_name) }}
            <span>Le nom latin de la famille, ex: Cichlidae.</span>
          </td>
        	<td class="popup">
        		{{ form_errors(form.common_name) }}
        		{{ form_widget(form.common_name) }}
            <span>Le nom commun de la famille, ex: Cichlidés.</span>
        	</td>
          <td>
            {{ form_errors(form.image) }}
            {{ form_widget(form.image) }}
          </td>
        </tr>
        <tr>
          <th colspan="3">{{ form_label(form.description, "Description") }}</th>
        </tr>
        <tr>
          <td class="popup" colspan="3">
            {{ form_errors(form.description) }}
            {{ form_widget(form.description) }}
            <span>Faire une description de la famille. Voici quelques pistes pour vous guider: Origine global, nombre d'éspèces recensées, l'ordre ou sous-ordre...</span>
          </td>
        </tr>
      </table>

      <table id="famille-poissons-table-form" class="famille-table-form">
        <tr>
          <th>{{ form_label(form.poissons, "Poissons") }}</th>
        </tr>
        <tr>
          <td>
            <p>Dans ce formulaire, pour des raisons de lisibilité, les informations concernant les poissons ajoutés sont minimales. De nombreuses informations pourrons être ajoutées dans le menu d'éditions du poisson en post-création.</p>
            {{ form_errors(form.poissons) }}
            {{ form_widget(form.poissons) }}
          </td>
        </tr>
      </table>

      <table>
        <tr>
          <td>
            {{ form_rest(form) }} {# Génération des champs pas encore écrits. Dans cet exemple, ce serait « image », mais aussi le champ CSRF (géré automatiquement par Symfony !) et tous les champs cachés (type « hidden »). #}
          </td>
        </tr>
      </table>
  	</form>
  </section>
{% endblock %}

{% block barre_lateral %}
  {% block barre_lateral_titre %}
    <h3>
      Menu famille
    </h3>
  {% endblock barre_lateral_titre %}
  {% block barre_lateral_navigation %}
    <ul>
      <li><a href="{{ path('biotopedia_pisciotheque_indexFamille') }}">
        Index famille</a></li>
      <li><a href="{{ path('biotopedia_pisciotheque_indexPoisson') }}">
        Index poisson</a></li>
    </ul>
  {% endblock barre_lateral_navigation %}
{% endblock barre_lateral %}

{% block javascripts %}
  <script src="{{ asset('js/jquery-2.1.3.js') }}"></script>
  {% javascripts '@BiotopediaPisciothequeBundle/Resources/public/js/Famille/addFamille.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
  {% endjavascripts %}
{% endblock %}

src/Biotopedia/PisciothequeBundle/Resources/views/Famille/deleteFamille.html.twig
{# src/Biotopedia/PisciothequeBundle/Resources/views/Famille/deleteFamille.html.twig #}

{% extends "BiotopediaPisciothequeBundle::layout.html.twig" %}

{% block title %}
  Supprimer un poisson - {{ parent() }}
{% endblock %}

{% block titre %}
  {{ parent() }}<h3 class="content-titre">Supprimer une famille</h3>
{% endblock %}

{% block biotopediapisciotheque_content %}
  <p>Etes-vous certain de vouloir supprimer la famille <b>"{{ famille.scientificName|capitalize }}"</b> ?</p>
  {# On met l'id de la famille dans la route de l'action du formulaire #}
  <form action="{{ path('biotopedia_pisciotheque_deleteFamille', {'id': famille.id}) }}" method="post">
    <a href="{{ path('biotopedia_pisciotheque_showFamille', {'id': famille.id}) }}" class="bouton">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la famille
    </a>
    {# Ici j'ai écrit le bouton de soumission à la main #}
    <input type="submit" value="Supprimer" class="bouton-danger" />
    {{ form_rest(form) }} {# Ceci va générer le champ CSRF #}
  </form> 
{% endblock %}

{% block barre_lateral %}
  {% block barre_lateral_titre %}
    <h3>
      Menu famille <b>{{ famille.scientificName|capitalize }}</b>
    </h3>
  {% endblock barre_lateral_titre %}
  {% block barre_lateral_navigation %}
    <ul>
      <li><a href="{{ path('biotopedia_pisciotheque_indexFamille') }}">
        Index famille</a></li>
      <li><a href="{{ path('biotopedia_pisciotheque_indexPoisson') }}">
        Index poisson</a></li>
      <li><a href="{{ path('biotopedia_pisciotheque_showFamille', { 'id': famille.id }) }}">
        Retour à la fiche famille <b>{{ famille.scientificName }}</b></a></li>
    </ul>
  {% endblock barre_lateral_navigation %}
{% endblock barre_lateral %}

src/Biotopedia/PisciothequeBundle/Resources/views/Famille/editFamille.html.twig
{# src/Biotopedia/PisciothequeBundle/Resources/views/Famille/editFamille.html.twig #}

{% extends "BiotopediaPisciothequeBundle::layout.html.twig" %}

{% block title %}
  Éditer une famille - {{ parent() }}
{% endblock %}

{% block titre %}
  {{ parent() }}<h3 class="content-titre">Éditer la famille</b></h3>
{% endblock %}

{% block biotopediapisciotheque_content %}
  <section id="form-editFamille">
    <p>Vous vous apprêtez à modifier la famille <b>{{ famille.scientificName|capitalize }}</b> dans la pisciothèque du site {{website}} !</p>
  	<form action="{{ path('biotopedia_pisciotheque_editFamille', { 'id': famille.id }) }}" method="post" {{ form_enctype(form) }}>

      <div class="error">
        {{ form_errors(form) }}{# Les erreurs générales du formulaire. #}
      </div>

      <table id="famille-identite-table-form" class="famille-table-form">
        <tr>
          <th>{{ form_label(form.scientific_name, "Nom Scientifique") }}</th>
          <th>{{ form_label(form.image, "Photo de la famille") }}</th>
        </tr>
        <tr>
          <td>
            {{ form_errors(form.scientific_name) }}
            {{ form_widget(form.scientific_name) }}
          </td>
          <td rowspan="3">
            <img class="#" src="{{ asset ((famille.image.webPath) | imagine_filter('my_thumb_out') ) }}" alt="{{ famille.image.alt }} image not found"/>
            Ajouter une photo écrasera l'ancienne ci-contre !
            <hr/>
            {{ form_errors(form.image) }}
            {{ form_widget(form.image) }}
          </td>
        </tr>
        <tr>
          <th>{{ form_label(form.common_name, "Nom Commun") }}</th>
        </tr>
        <tr>
          <td>
            {{ form_errors(form.common_name) }}
            {{ form_widget(form.common_name) }}
          </td>
        </tr>
        <tr>
          <th colspan="3">{{ form_label(form.description, "Description") }}</th>
        </tr>
        <tr>
          <td colspan="3">
            {{ form_errors(form.description) }}
            {{ form_widget(form.description) }}
          </td>
        </tr>
      </table>

      <table>
        <tr>
          <td>
            {{ form_rest(form) }} {# Génération des champs pas encore écrits. Dans cet exemple, ce serait « image », mais aussi le champ CSRF (géré automatiquement par Symfony !) et tous les champs cachés (type « hidden »). #}
          </td>
        </tr>
      </table>
    </form>
  </section>
{% endblock %}

{% block barre_lateral %}
  {% block barre_lateral_titre %}
    <h3>
      Menu famille <b>{{ famille.scientificName|capitalize }}</b>
    </h3>
  {% endblock barre_lateral_titre %}
  {% block barre_lateral_navigation %}
    <ul>
      <li><a href="{{ path('biotopedia_pisciotheque_indexFamille') }}">
        Index famille</a></li>
      <li><a href="{{ path('biotopedia_pisciotheque_indexPoisson') }}">
        Index poisson</a></li>
      <li><a href="{{ path('biotopedia_pisciotheque_showFamille', { 'id': famille.id }) }}">
        Retour à la fiche famille <b>{{ famille.scientificName }}</b></a></li>
    </ul>
  {% endblock barre_lateral_navigation %}
{% endblock barre_lateral %}

{% block javascripts %}
  <script src="{{ asset('js/jquery-2.1.3.js') }}"></script>
  {% javascripts '@BiotopediaPisciothequeBundle/Resources/public/js/Famille/editFamille.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
  {% endjavascripts %}
	</script>
{% endblock %}

src/Biotopedia/PisciothequeBundle/Resources/views/Famille/index.html.twig
{# src/Biotopedia/PisciothequeBundle/Resources/views/Famille/index.html.twig #}

{% extends "BiotopediaPisciothequeBundle::layout.html.twig" %}

{% block title %}
   Index famille - {{ parent() }}
{% endblock %}

{% block titre %}
  {{ parent() }}<h3 class="content-titre">Index familles</h3>
{% endblock %}

{% block biotopediapisciotheque_content %}

	<p>Hello,</br>
		Bienvenue sur la Pisciothèque, la banque de données de poissons du site {{ website }} !</br>
		Cette dernière a pour vocation, le regroupement de poissons et leurs informations déstinées aux aquariphiles et autres.</br>
		Voici les Familles de Poissons présentes sur le site :
	</p>
	
	<nav id="navigateur-famille">
	{% for famille in familles %}
		<a class = "index-famille" href = "{{ path('biotopedia_pisciotheque_showFamille', { 'id': famille.id }) }}">
		<table style = "background-image: url({{ asset ((famille.image.webPath) | imagine_filter('my_thumb_out')) }});">
			<thead>
				<tr>
					<th>
						<a href="{{ path('biotopedia_pisciotheque_showFamille', { 'id': famille.id }) }}">
							{{ famille.scientificName }} ({{ famille.nbPoissons }})</a>
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
					</td>
				</tr>
			</tbody>
		</table>
		</a>
	{% endfor %}
	</nav>
{% endblock %}

{% block barre_lateral %}
    {% block barre_lateral_titre %}<h3>Menu famille</h3>{% endblock barre_lateral_titre %}
      {% block barre_lateral_navigation %}
            <ul>
                <li><a href="{{ path('biotopedia_pisciotheque_addFamille')}}">
                    Ajouter une famille</a></li>
                <li><a href="{{ path('biotopedia_pisciotheque_indexPoisson')}}">
                    Index des poissons</a></li>
            </ul>
      {% endblock barre_lateral_navigation %}
{% endblock barre_lateral %}

src/Biotopedia/PisciothequeBundle/Resources/views/Famille/showFamille.html.twig
{# src/Biotopedia/PisciothequeBundle/Resources/views/Famille/showFamille.html.twig #}

{% extends "BiotopediaPisciothequeBundle::layout.html.twig" %}

{% block title %}
    Fiche famille - {{ parent() }}
{% endblock %}

{% block titre %}
    {{ parent() }}<h3 class="content-titre">Fiche famille</h3>
{% endblock %}

{% block biotopediapisciotheque_content %}
    <article id="famille-show">
        {% if famille.image.webPath is not null %}
            <a class="link-image" href="{{ path('biotopedia_core_showImage', { 'id': famille.image.id }) }}"><img class="#" src="{{ asset ((famille.image.webPath) | imagine_filter('my_widen') ) }}" alt="{{ famille.image.alt }} image not found"/></a>
        {% else %}
            <p class="var-non-definie">{{ var_non_definie }}</p>
        {% endif %}
        <header>
            <h2>{{ famille.scientificName }} ({{ famille.commonName }})</h2>
            {% if famille.updated is not null %}
                <time datetime="{{ famille.updated | date('c') }}">Éditée le {{ famille.updated | localizeddate('full', 'none') }}</time>
            {% else %}
                <time datetime="{{ famille.created | date('c') }}">Rédigé le {{ famille.created | localizeddate('full', 'none') }}</time>
            {% endif %}
        </header>
        <p>
            {{ famille.description }}
        </p>
        <footer>
            {% if not famille.auteurs.empty %}
                <table>
                    <tr>
                        {% for auteur in famille.auteurs %}
                        <td>
                            <a href="{{ path('bp_users_showUser', { 'id': auteur.id }) }}" rel="author">
                                <img src="{{ auteur.email|getGravatarImage(40)}}" alt=""/>
                                {{ auteur.username }}
                            </a>
                        </td>
                        {% endfor %}
                    </tr>
                </table>
            {% endif %}
        </footer>

        <div id="famille-poissons">
            <header><h3>{{ 'Poissons appartenant à la famille '|upper }}{{ famille.scientificName|upper }}</h3></header>
            <div class="table-liste">
                <table>
                    <thead>
                        <tr>
                            <th>Nom Commun</th>
                            <th>Nom Scientifique</th>
                            <th>Auteur </th>
                            <th>Date de création</th>
                            <th>Dernière mise à jour</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if not famille.poissons.empty %}
                        {% for poisson in famille.poissons %}
                        <tr>
                            <td><a href="{{ path('biotopedia_pisciotheque_showPoisson', { 'id': poisson.id }) }}">{{ poisson.commonName }}</a>
                            </td>
                            <td><a href="{{ path('biotopedia_pisciotheque_showPoisson', { 'id': poisson.id }) }}">{{ poisson.scientificName }}</a>
                            </td>
                            <td>
                                {% if not poisson.auteurs.empty %}
                                    {% for auteur in poisson.auteurs %}
                                        <a href="{{ path('bp_users_showUser', { 'id': auteur.id }) }}">{{ auteur.username }}</a>
                                        {% if not loop.last %}, {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </td>
                            <td><a href="{{ path('biotopedia_pisciotheque_showPoisson', { 'id': poisson.id }) }}"><time  datetime="{{ poisson.created | date('c') }}">{{ poisson.created | localizeddate('full', 'none')   }}</time></a>
                            </td>
                            <td><a href="{{ path('biotopedia_pisciotheque_showPoisson', { 'id': poisson.id }) }}">
                                {% if poisson.updated is not null %}
                                    <time datetime="{{ poisson.updated | date('c') }}">{{ poisson.updated | localizeddate('full', 'none') }}</time></a>
                                {% else %}
                                    ~
                                {% endif %}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        <tr><td colspan="5">Aucun poisson n'a été rédiger pour la famille {{ famille.commonName }}, pour le moment ! Rejoignez la communauté et soyez le premier a poster un poisson dans cette famille.</td></tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </article>
{% endblock %}

{% block barre_lateral %}
    {% block barre_lateral_titre %}
        <h3>
        {% if is_granted('ROLE_USER') %}
             Administration de {{ famille.scientificName | title }}
        {% else %}
            Menu famille
        {% endif %}
        </h3>
    {% endblock barre_lateral_titre %}
    {% block barre_lateral_navigation %}
        <ul>
            <li><a href="{{ path('biotopedia_pisciotheque_indexFamille') }}">
                Index des familles</a></li>
            <li><a href="{{ path('biotopedia_pisciotheque_indexPoisson') }}">
                Index des poissons</a></li>
            <li><a href="{{ path('biotopedia_pisciotheque_addFamille') }}">
                 Ajouter une nouvelle famille</a></li>
            <li><a href="{{ path('biotopedia_pisciotheque_addPoisson', { 'id': famille.id }) }}">
                 Ajouter un poisson à la famille</a></li>
            <li><a href="{{ path('biotopedia_pisciotheque_editFamille', { 'id': famille.id }) }}">
                Éditer cette famille</a></li>
            {% if is_granted('ROLE_ADMIN') %}
                <li><a href="{{ path('biotopedia_pisciotheque_deleteFamille', { 'id': famille.id }) }}">
                    Supprimer la famille</a></li>
            {% endif %}
        {% for auteur in famille.auteurs %}
            {% if app.user.username is defined and auteur.username == app.user.username %}
                <li><a href="{{ path('biotopedia_pisciotheque_deleteFamille', { 'id': famille.id }) }}">
                    Demande de suppression de la famille</a></li>
            {% endif %}
        {% endfor %}
        </ul>
    {% endblock barre_lateral_navigation %}
{% endblock barre_lateral %}